language: java
sudo: false
jdk:
- openjdk8
- openjdk11
before_install:
  - chmod +x ./gradlew
script:
  - xvfb-run ./gradlew check
  - ./gradlew javadoc
  - ./gradlew jacocoTestReport
deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew bintrayUpload -Ddeployment=true
    on:
      tags: true
      jdk: openjdk11
after_success:
   - bash <(curl -s https://codecov.io/bash)
